micronaut:
  application:
    name: convertPdfToWord
netty:
  default:
    allocator:
      max-order: 3
  micronaut:
    server:
       max-request-size: '100MB'
       multipart:
           max-file-size: '100MB'